Fix benchmark plotting for one argument
If there is only one axis, pyplot returns the single axis rather than an array by default. This caused the plotting code to produce this error:
```
Bens-MacBook-Pro-4:program bhannel$ python3 bench_plot.py rlu.csv RLU
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "bench_plot.py", line 31, in <module>
    main()
  File "bench_plot.py", line 20, in main
    ax = axes[i]
TypeError: 'AxesSubplot' object does not support indexing
```

To fix it, we can explicitly specify `squeeze=False`, and we then get a 2 dimensional array regardless of the number of axes.